import { useEffect } from 'react';

interface Props {
  onClose: () => void;
}

const GENERATION_MODES = [
  {
    title: 'Web Search (default)',
    body: 'A three-step pipeline: Claude plans which recipes fit your preferences and picks a plausible source site, Tavily searches the web and extracts the real ingredient list and instructions from that page, then Claude writes the final recipe using that real content — so it can\'t contradict an actual published recipe.',
  },
  {
    title: 'AI Generated',
    body: 'A single step: Claude writes the recipe entirely from its own training knowledge, with no web search at all. Faster, but not sourced from a real page — look for the "Generated by Claude" note instead of a source link. Toggle between the two in the sidebar\'s "Recipe Search" section; it applies to full-plan generation and selective regeneration alike.',
  },
];

const MATCH_STEPS = [
  { n: '1', heading: 'Non-food exclusion', body: 'Candy/gum, personal care, household, pet, and similar categories are dropped outright, even on a strong text match — searching "mint leaves" won\'t return breath mints.' },
  { n: '2', heading: 'Recipe-speak → retail-speak', body: 'A table of known naming differences (scallion ↔ green onion, cilantro ↔ coriander, garbanzo ↔ chickpea, and more) is applied so a differently-worded product still counts as a real match.' },
  { n: '3', heading: 'Full word coverage', body: 'A candidate only counts as a strong match if every meaningful word in the ingredient appears in its description — "toasted rice powder" needs more than a product that merely says "rice."' },
  { n: '4', heading: 'Phrase adjacency', body: 'Among candidates tied on word coverage, ones where the words appear together as a phrase are preferred over the same words scattered incidentally through the description.' },
  { n: '5', heading: 'Department plausibility', body: 'Products from actual cooking-ingredient departments (produce, meat, dairy, spices, grains, baking, international, etc.) are preferred over snacks or beverages that just happen to share a flavor name.' },
  { n: '6', heading: 'Quantity matching', body: 'Needing 6 onions and finding a 3-count bag adds 2 to the cart, not 1 — but only for unambiguous units (an explicit pack count, or a unit that IS the package, like "can" or "jar"). Ambiguous units like "cloves" or "slices" are never guessed.' },
  { n: '7', heading: 'Remembered corrections', body: 'Manually picking a different product for an ingredient is remembered for next time, per browser. Removing a pick without choosing a replacement excludes that product from future auto-picks for that ingredient.' },
];

const CLAUDE_FEATURES = [
  {
    title: 'Ask Claude to Verify',
    body: 'Sends just the ⚠ Verify-flagged items (or everything, via a checkbox) to Claude in one batched request, along with which recipe(s) the ingredient is used in and their cuisine — so it can tell "Thai chili" needs an actual Thai variety, not just any hot pepper.',
  },
  {
    title: 'Let Claude pick directly',
    body: 'Skips the algorithm entirely — Claude picks (or explicitly declines to pick) every ingredient from the start. Remembered corrections and exclusions still apply first. If the request fails (e.g. rate limited), it falls back to the algorithm automatically rather than leaving the list empty.',
  },
];

export default function HowItWorksModal({ onClose }: Props) {
  useEffect(() => {
    const onKey = (e: KeyboardEvent) => { if (e.key === 'Escape') onClose(); };
    document.addEventListener('keydown', onKey);
    document.body.style.overflow = 'hidden';
    return () => {
      document.removeEventListener('keydown', onKey);
      document.body.style.overflow = '';
    };
  }, [onClose]);

  return (
    <div className="modal-backdrop" onClick={onClose}>
      <div
        className="help-modal how-it-works-modal"
        onClick={(e) => e.stopPropagation()}
        role="dialog"
        aria-modal="true"
        aria-label="How SempAI works"
      >
        <div className="help-modal__header">
          <div>
            <h2 className="help-modal__title">How it works</h2>
            <p className="help-modal__subtitle">Recipe generation, shopping matching, and where Claude fits into each</p>
          </div>
          <button className="modal__close" onClick={onClose} aria-label="Close">✕</button>
        </div>

        <div className="help-modal__body">
          <section className="help-modal__section">
            <h3 className="help-modal__section-title">Recipe generation — two pipelines</h3>
            <div className="how-it-works__cards">
              {GENERATION_MODES.map((m) => (
                <div key={m.title} className="how-it-works__card">
                  <div className="how-it-works__card-title">{m.title}</div>
                  <p className="how-it-works__card-body">{m.body}</p>
                </div>
              ))}
            </div>
          </section>

          <section className="help-modal__section">
            <h3 className="help-modal__section-title">Shopping list — product-matching algorithm</h3>
            <p className="how-it-works__intro">
              Before any Kroger matching happens, the list itself merges ingredients that mean the same thing — plural/singular
              variants ("Shallot"/"Shallots"), hyphenation, quality qualifiers ("extra virgin olive oil" vs. "olive oil"), and
              recipe-speak/retail-speak synonyms (scallion/green onion) all collapse into one row, keeping whichever wording is
              more descriptive.
            </p>
            <p className="how-it-works__intro">
              Clicking "Find Products" then runs every ingredient through these layers, in order, before picking a product:
            </p>
            <ol className="help-steps">
              {MATCH_STEPS.map((s) => (
                <li key={s.n} className="help-step">
                  <span className="help-step__num">{s.n}</span>
                  <div>
                    <div className="help-step__heading">{s.heading}</div>
                    <div className="help-step__body">{s.body}</div>
                  </div>
                </li>
              ))}
            </ol>
            <p className="how-it-works__intro">
              An <strong>Accurate / Balanced / Cheapest</strong> toggle (next to "Find Products") controls how many already-vetted
              candidates get price-compared — widening it never reopens a wrong-category or wrong-form match, it only decides which
              of several already-valid options wins on price. Picks the algorithm isn't fully confident about are flagged{' '}
              <strong>⚠ Verify</strong> and sorted to the top of the list.
            </p>
          </section>

          <section className="help-modal__section">
            <h3 className="help-modal__section-title">Claude-assisted shopping matching (Full Access only)</h3>
            <div className="how-it-works__cards">
              {CLAUDE_FEATURES.map((f) => (
                <div key={f.title} className="how-it-works__card">
                  <div className="how-it-works__card-title">{f.title}</div>
                  <p className="how-it-works__card-body">{f.body}</p>
                </div>
              ))}
            </div>
            <p className="how-it-works__intro">
              Either way, if none of the candidates are a genuine match, Claude says so explicitly ("no suitable match") instead of
              forcing a substitute — you can search Kroger's site directly or pick manually from the same candidates it saw. Both
              features require <strong>Full Access</strong>; in Demo Mode the controls stay visible but locked, with a short
              explainer on click.
            </p>
          </section>

          <section className="help-modal__section">
            <h3 className="help-modal__section-title">Manual review mode (no Full Access required)</h3>
            <p className="how-it-works__intro">
              From "Review Cart," click <strong>Manually Review Items</strong> to choose your own scope — just the flagged items,
              everything, or a custom checkbox selection — then step through them one at a time with Back/Next. Each ingredient
              shows only its top few candidates (6 by default, with a "show all" link), ranked by SempAI's own relevance scoring
              or Kroger's own order; you can switch to price or name instead, and that sort choice is remembered across
              ingredients and future shopping trips. A manual pick here is remembered the same as any other correction.
            </p>
          </section>

          <section className="help-modal__section">
            <h3 className="help-modal__section-title">Full Access &amp; Demo Mode</h3>
            <p className="how-it-works__intro">
              By default the app runs in <strong>Demo Mode</strong>: 2 AI meal-plan generations per day, and the Claude shopping
              features above are locked (the automatic matching algorithm still works fully). Visiting the app via a{' '}
              <strong>Full Access</strong> link raises that to 10/day and unlocks the Claude features. Your current mode is shown
              as a badge in the top-right of the page.
            </p>
          </section>
        </div>

        <div className="help-modal__footer">
          <button className="btn-primary" onClick={onClose}>Close</button>
        </div>
      </div>
    </div>
  );
}
